### ISSUE TITLE
gnatmake: "ewdsefil" not found

### ISSUE THREAD

**Issue by cedorfgt** [dsanson/Words#1]
Words$ gnatmake ewdsefil
gnatmake: "ewdsefil" not found

thats what I get after trying to compile the git file from the "words" directory. My machine is a xubuntu 14.10 64 bits

help appreciated.

**Comment by dsanson** [comment]
I am confused! Some how some of the instructions seem to have gotten corrupted. If you search this repo for `gnatmake` (https://github.com/dsanson/Words/search?utf8=%E2%9C%93&q=gnatmake), you can see that the README and wordsdoc.html contain that `gnatmake ewdsefil` line,

```
gnatmake -O3 words 
gnatmake makedict 
gnatmake makestem 
gnatmake ewdsefil 
gnatmake makeinfl
```

but the `HOWTO.txt` has a different set of build commands:

```
gnatmake -O3 words
gnatmake -O3 makedict
gnatmake -O3 makestem
gnatmake -O3 makeewds
gnatmake -O3 makeefil
gnatmake -O3 makeinfl
```

These are the commands that https://github.com/maw/words recommends, too.

Where did those directions in the README and wordsdoc.htm come from? According to this page, http://archives.nd.edu/whitaker/wordsdev.htm, the appropriate build commands are:

```
gnatmake -O3 words
gnatmake makedict
gnatmake makestem
gnatmake makeefil
gnatmake makeinfl
```

So you could also try replacing the rogue `ewdsefil` with `makeefil`...

Let me know what works, and I'll fix the README.
